sudo: required
services:
  - docker

before_install:
  - docker build -t mkozi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mkozi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "mkozi-docker-react"
  env: "MkoziDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-984507794590"
  bucket_path: "mkozi-docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access key:
    secure: $AWS_SECRET_KEY
